### ISSUE TITLE
Add Php requirements to documentation

### ISSUE THREAD

**Issue by digistorm** [beyondcode/laravel-prose-linter#7]
If you install the package you will get:
`composer require beyondcode/laravel-prose-linter`

                                                                                                                                         
```  [InvalidArgumentException]                                                                                                             
  Package beyondcode/laravel-prose-linter has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  
  ``` 
  
  Php 8 is required to install this package.

**Comment by mechelon** [comment]
Added in 2.0
